== Spock vs Supermutants
=== Specification testing meets mutation testing

The Spock test framework uses the expressive Groovy to realize BDD as a test approach.
Besides a clear test structure, it scores with readable reports, which can also be generated in AsciiDoc thanks to a
template engine. Can this be improved? We take the proof and combine Spock with mutation tests.
Because a test coverage of over 80% does not yet prove that the test suite is capable of reliably detecting errors. The presentation shows how Spock can be combined with mutation tests to form a clever duo.

This repository contains the source code for the presentation of the same name:

https://www.code-days.de/programm/programm-details/411/spock-vs-supermutanten-spezifikationstesten-trifft-mutationstesten/[Code Days 2020] 04.02.2020 in München

A recording can be found at https://youtu.be/VUpPAE5aM0I[Spock vs Supermutanten @ Cyberland]

=== Usage

* `./gradlew` executes all Unit-Tests through Spock, executes Pitest and generates an AsciiDoc-Report

== License

The content of this repository is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 license].

